name: Deploy to Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PROJECT_ID: kavisha-ai-468913
  REGION: us-central1
  REPOSITORY: web

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_environment_variables: true

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Docker auth to Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Set image tag (git SHA)
        run: echo "IMAGE=us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/app:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build image (once)
        run: docker build -t $IMAGE .

      - name: Push image (once)
        run: docker push $IMAGE

      # Update all services to the same image. Services must already exist with envs set.
      - name: Deploy yt-video-audio
        run: gcloud run services update yt-video-audio --image $IMAGE --region ${{ env.REGION }} --platform managed
